version: '3.9'

services:

  razor:
    container_name: razor
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
    networks:
      - backend


networks:
  backend:
    name: backend